version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservation_app
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env.docker
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: >
      sh -c "
      echo 'ðŸš€ Ejecutando migraciones en Supabase...';
      npx prisma migrate deploy;
      echo 'ðŸŒ± Ejecutando seed (solo si es necesario)...';
      npx prisma db seed;
      echo 'âœ… Iniciando Next.js...';
      npm run dev
      "

volumes:
  node_modules:
